/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro.com.github.bohunn;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

import jakarta.xml.bind.DatatypeConverter;
import java.io.IOException;
import org.springframework.util.DigestUtils;

@org.apache.avro.specific.AvroGenerated
public class JoinedBpAddrV2 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord, TypedEntity {
  private static final long serialVersionUID = -6742914784131239291L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"JoinedBpAddrV2\",\"namespace\":\"avro.com.github.bohunn\",\"fields\":[{\"name\":\"bpObjId\",\"type\":\"long\",\"doc\":\"obj_bp id\"},{\"name\":\"bpName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"bpNr\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"obj_bp key id 11\"},{\"name\":\"closeDate\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"isMa\",\"type\":\"boolean\"},{\"name\":\"isVip\",\"type\":\"boolean\"},{\"name\":\"isBanklagernd\",\"type\":\"boolean\"},{\"name\":\"domiAddrId\",\"type\":\"long\",\"doc\":\"Domicil Address object id\"},{\"name\":\"mainAddrId\",\"type\":\"long\"},{\"name\":\"mainAddresse\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"isJoint\",\"type\":\"boolean\"},{\"name\":\"relationList\",\"type\":[\"null\",{\"type\":\"array\",\"items\":[\"null\",{\"type\":\"record\",\"name\":\"RelationItem\",\"fields\":[{\"name\":\"relationType\",\"type\":{\"type\":\"enum\",\"name\":\"RelationType\",\"doc\":\"RO - Registered Owner, AO - Account Owner, IO - Issuer\",\"symbols\":[\"RO\",\"AO\",\"IO\"],\"default\":\"AO\"},\"doc\":\"Relation Type\"},{\"name\":\"personObjId\",\"type\":\"long\",\"doc\":\"obj_person id of a related person\"},{\"name\":\"validFrom\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"relation valid from date\"},{\"name\":\"validTo\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"relation valid to date\"}]}],\"default\":\"null\"}],\"doc\":\"Bp-Person relation list\"},{\"name\":\"force\",\"type\":\"int\",\"doc\":\"technical field to force onbase synchronization\"},{\"name\":\"hash\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<JoinedBpAddrV2> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<JoinedBpAddrV2> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<JoinedBpAddrV2> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<JoinedBpAddrV2> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<JoinedBpAddrV2> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this JoinedBpAddrV2 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a JoinedBpAddrV2 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a JoinedBpAddrV2 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static JoinedBpAddrV2 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** obj_bp id */
  private long bpObjId;
  private java.lang.String bpName;
  /** obj_bp key id 11 */
  private java.lang.String bpNr;
  private java.lang.String closeDate;
  private boolean isMa;
  private boolean isVip;
  private boolean isBanklagernd;
  /** Domicil Address object id */
  private long domiAddrId;
  private long mainAddrId;
  private java.lang.String mainAddresse;
  private boolean isJoint;
  /** Bp-Person relation list */
  private java.util.List<avro.com.github.bohunn.RelationItem> relationList;
  /** technical field to force onbase synchronization */
  private int force;
  private java.lang.String hash;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public JoinedBpAddrV2() {}

  /**
   * All-args constructor.
   * @param bpObjId obj_bp id
   * @param bpName The new value for bpName
   * @param bpNr obj_bp key id 11
   * @param closeDate The new value for closeDate
   * @param isMa The new value for isMa
   * @param isVip The new value for isVip
   * @param isBanklagernd The new value for isBanklagernd
   * @param domiAddrId Domicil Address object id
   * @param mainAddrId The new value for mainAddrId
   * @param mainAddresse The new value for mainAddresse
   * @param isJoint The new value for isJoint
   * @param relationList Bp-Person relation list
   * @param force technical field to force onbase synchronization
   * @param hash The new value for hash
   */
  public JoinedBpAddrV2(java.lang.Long bpObjId, java.lang.String bpName, java.lang.String bpNr, java.lang.String closeDate, java.lang.Boolean isMa, java.lang.Boolean isVip, java.lang.Boolean isBanklagernd, java.lang.Long domiAddrId, java.lang.Long mainAddrId, java.lang.String mainAddresse, java.lang.Boolean isJoint, java.util.List<avro.com.github.bohunn.RelationItem> relationList, java.lang.Integer force, java.lang.String hash) {
    this.bpObjId = bpObjId;
    this.bpName = bpName;
    this.bpNr = bpNr;
    this.closeDate = closeDate;
    this.isMa = isMa;
    this.isVip = isVip;
    this.isBanklagernd = isBanklagernd;
    this.domiAddrId = domiAddrId;
    this.mainAddrId = mainAddrId;
    this.mainAddresse = mainAddresse;
    this.isJoint = isJoint;
    this.relationList = relationList;
    this.force = force;
    this.hash = hash;
  }

   /**
   * Constructor with automatic hash value calc
   * @param bpObjId obj_bp id
   * @param bpName The new value for bpName
   * @param bpNr obj_bp key id 11
   * @param closeDate The new value for closeDate
   * @param isMa The new value for isMa
   * @param isVip The new value for isVip
   * @param isBanklagernd The new value for isBanklagernd
   * @param domiAddrId Domicil Address object id
   * @param mainAddrId The new value for mainAddrId
   * @param mainAddresse The new value for mainAddresse
   * @param isJoint The new value for isJoint
   * @param relationList The new value for relationList
   * @param force technical field to force onbase synchronization
   */
  public JoinedBpAddrV2(java.lang.Long bpObjId, java.lang.String bpName, java.lang.String bpNr, java.lang.String closeDate, java.lang.Boolean isMa, java.lang.Boolean isVip, java.lang.Boolean isBanklagernd, java.lang.Long domiAddrId, java.lang.Long mainAddrId, java.lang.String mainAddresse, java.lang.Boolean isJoint, java.util.List<avro.com.github.bohunn.RelationItem> relationList, java.lang.Integer force) {
    this.bpObjId = bpObjId;
    this.bpName = bpName;
    this.bpNr = bpNr;
    this.closeDate = closeDate;
    this.isMa = isMa;
    this.isVip = isVip;
    this.isBanklagernd = isBanklagernd;
    this.domiAddrId = domiAddrId;
    this.mainAddrId = mainAddrId;
    this.mainAddresse = mainAddresse;
    this.isJoint = isJoint;
    this.relationList = relationList;
    this.hash = "dummy";
    this.force = force;
    try {
      byte[] md5Digest = DigestUtils.md5Digest(getEncoder().encode(this).array());
      this.hash = DatatypeConverter.printHexBinary(md5Digest);
    } catch (JsonProcessingException var18) {
      throw new RuntimeException(var18);
    } catch (IOException var19) {
      throw new IllegalStateException(var19);
    }
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bpObjId;
    case 1: return bpName;
    case 2: return bpNr;
    case 3: return closeDate;
    case 4: return isMa;
    case 5: return isVip;
    case 6: return isBanklagernd;
    case 7: return domiAddrId;
    case 8: return mainAddrId;
    case 9: return mainAddresse;
    case 10: return isJoint;
    case 11: return relationList;
    case 12: return force;
    case 13: return hash;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bpObjId = (java.lang.Long)value$; break;
    case 1: bpName = value$ != null ? value$.toString() : null; break;
    case 2: bpNr = value$ != null ? value$.toString() : null; break;
    case 3: closeDate = value$ != null ? value$.toString() : null; break;
    case 4: isMa = (java.lang.Boolean)value$; break;
    case 5: isVip = (java.lang.Boolean)value$; break;
    case 6: isBanklagernd = (java.lang.Boolean)value$; break;
    case 7: domiAddrId = (java.lang.Long)value$; break;
    case 8: mainAddrId = (java.lang.Long)value$; break;
    case 9: mainAddresse = value$ != null ? value$.toString() : null; break;
    case 10: isJoint = (java.lang.Boolean)value$; break;
    case 11: relationList = (java.util.List<avro.com.github.bohunn.RelationItem>)value$; break;
    case 12: force = (java.lang.Integer)value$; break;
    case 13: hash = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'bpObjId' field.
   * @return obj_bp id
   */
  public long getBpObjId() {
    return bpObjId;
  }


  /**
   * Sets the value of the 'bpObjId' field.
   * obj_bp id
   * @param value the value to set.
   */
  public void setBpObjId(long value) {
    this.bpObjId = value;
  }

  /**
   * Gets the value of the 'bpName' field.
   * @return The value of the 'bpName' field.
   */
  public java.lang.String getBpName() {
    return bpName;
  }


  /**
   * Sets the value of the 'bpName' field.
   * @param value the value to set.
   */
  public void setBpName(java.lang.String value) {
    this.bpName = value;
  }

  /**
   * Gets the value of the 'bpNr' field.
   * @return obj_bp key id 11
   */
  public java.lang.String getBpNr() {
    return bpNr;
  }


  /**
   * Sets the value of the 'bpNr' field.
   * obj_bp key id 11
   * @param value the value to set.
   */
  public void setBpNr(java.lang.String value) {
    this.bpNr = value;
  }

  /**
   * Gets the value of the 'closeDate' field.
   * @return The value of the 'closeDate' field.
   */
  public java.lang.String getCloseDate() {
    return closeDate;
  }


  /**
   * Sets the value of the 'closeDate' field.
   * @param value the value to set.
   */
  public void setCloseDate(java.lang.String value) {
    this.closeDate = value;
  }

  /**
   * Gets the value of the 'isMa' field.
   * @return The value of the 'isMa' field.
   */
  public boolean getIsMa() {
    return isMa;
  }


  /**
   * Sets the value of the 'isMa' field.
   * @param value the value to set.
   */
  public void setIsMa(boolean value) {
    this.isMa = value;
  }

  /**
   * Gets the value of the 'isVip' field.
   * @return The value of the 'isVip' field.
   */
  public boolean getIsVip() {
    return isVip;
  }


  /**
   * Sets the value of the 'isVip' field.
   * @param value the value to set.
   */
  public void setIsVip(boolean value) {
    this.isVip = value;
  }

  /**
   * Gets the value of the 'isBanklagernd' field.
   * @return The value of the 'isBanklagernd' field.
   */
  public boolean getIsBanklagernd() {
    return isBanklagernd;
  }


  /**
   * Sets the value of the 'isBanklagernd' field.
   * @param value the value to set.
   */
  public void setIsBanklagernd(boolean value) {
    this.isBanklagernd = value;
  }

  /**
   * Gets the value of the 'domiAddrId' field.
   * @return Domicil Address object id
   */
  public long getDomiAddrId() {
    return domiAddrId;
  }


  /**
   * Sets the value of the 'domiAddrId' field.
   * Domicil Address object id
   * @param value the value to set.
   */
  public void setDomiAddrId(long value) {
    this.domiAddrId = value;
  }

  /**
   * Gets the value of the 'mainAddrId' field.
   * @return The value of the 'mainAddrId' field.
   */
  public long getMainAddrId() {
    return mainAddrId;
  }


  /**
   * Sets the value of the 'mainAddrId' field.
   * @param value the value to set.
   */
  public void setMainAddrId(long value) {
    this.mainAddrId = value;
  }

  /**
   * Gets the value of the 'mainAddresse' field.
   * @return The value of the 'mainAddresse' field.
   */
  public java.lang.String getMainAddresse() {
    return mainAddresse;
  }


  /**
   * Sets the value of the 'mainAddresse' field.
   * @param value the value to set.
   */
  public void setMainAddresse(java.lang.String value) {
    this.mainAddresse = value;
  }

  /**
   * Gets the value of the 'isJoint' field.
   * @return The value of the 'isJoint' field.
   */
  public boolean getIsJoint() {
    return isJoint;
  }


  /**
   * Sets the value of the 'isJoint' field.
   * @param value the value to set.
   */
  public void setIsJoint(boolean value) {
    this.isJoint = value;
  }

  /**
   * Gets the value of the 'relationList' field.
   * @return Bp-Person relation list
   */
  public java.util.List<avro.com.github.bohunn.RelationItem> getRelationList() {
    return relationList;
  }


  /**
   * Sets the value of the 'relationList' field.
   * Bp-Person relation list
   * @param value the value to set.
   */
  public void setRelationList(java.util.List<avro.com.github.bohunn.RelationItem> value) {
    this.relationList = value;
  }

  /**
   * Gets the value of the 'force' field.
   * @return technical field to force onbase synchronization
   */
  public int getForce() {
    return force;
  }


  /**
   * Sets the value of the 'force' field.
   * technical field to force onbase synchronization
   * @param value the value to set.
   */
  public void setForce(int value) {
    this.force = value;
  }

  /**
   * Gets the value of the 'hash' field.
   * @return The value of the 'hash' field.
   */
  public java.lang.String getHash() {
    return hash;
  }


  /**
   * Sets the value of the 'hash' field.
   * @param value the value to set.
   */
  public void setHash(java.lang.String value) {
    this.hash = value;
  }

  /**
   * Creates a new JoinedBpAddrV2 RecordBuilder.
   * @return A new JoinedBpAddrV2 RecordBuilder
   */
  public static avro.com.github.bohunn.JoinedBpAddrV2.Builder newBuilder() {
    return new avro.com.github.bohunn.JoinedBpAddrV2.Builder();
  }

  /**
   * Creates a new JoinedBpAddrV2 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new JoinedBpAddrV2 RecordBuilder
   */
  public static avro.com.github.bohunn.JoinedBpAddrV2.Builder newBuilder(avro.com.github.bohunn.JoinedBpAddrV2.Builder other) {
    if (other == null) {
      return new avro.com.github.bohunn.JoinedBpAddrV2.Builder();
    } else {
      return new avro.com.github.bohunn.JoinedBpAddrV2.Builder(other);
    }
  }

  /**
   * Creates a new JoinedBpAddrV2 RecordBuilder by copying an existing JoinedBpAddrV2 instance.
   * @param other The existing instance to copy.
   * @return A new JoinedBpAddrV2 RecordBuilder
   */
  public static avro.com.github.bohunn.JoinedBpAddrV2.Builder newBuilder(avro.com.github.bohunn.JoinedBpAddrV2 other) {
    if (other == null) {
      return new avro.com.github.bohunn.JoinedBpAddrV2.Builder();
    } else {
      return new avro.com.github.bohunn.JoinedBpAddrV2.Builder(other);
    }
  }

  /**
   * RecordBuilder for JoinedBpAddrV2 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<JoinedBpAddrV2>
    implements org.apache.avro.data.RecordBuilder<JoinedBpAddrV2> {

    /** obj_bp id */
    private long bpObjId;
    private java.lang.String bpName;
    /** obj_bp key id 11 */
    private java.lang.String bpNr;
    private java.lang.String closeDate;
    private boolean isMa;
    private boolean isVip;
    private boolean isBanklagernd;
    /** Domicil Address object id */
    private long domiAddrId;
    private long mainAddrId;
    private java.lang.String mainAddresse;
    private boolean isJoint;
    /** Bp-Person relation list */
    private java.util.List<avro.com.github.bohunn.RelationItem> relationList;
    /** technical field to force onbase synchronization */
    private int force;
    private java.lang.String hash;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.com.github.bohunn.JoinedBpAddrV2.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bpObjId)) {
        this.bpObjId = data().deepCopy(fields()[0].schema(), other.bpObjId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.bpName)) {
        this.bpName = data().deepCopy(fields()[1].schema(), other.bpName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.bpNr)) {
        this.bpNr = data().deepCopy(fields()[2].schema(), other.bpNr);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.closeDate)) {
        this.closeDate = data().deepCopy(fields()[3].schema(), other.closeDate);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.isMa)) {
        this.isMa = data().deepCopy(fields()[4].schema(), other.isMa);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.isVip)) {
        this.isVip = data().deepCopy(fields()[5].schema(), other.isVip);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.isBanklagernd)) {
        this.isBanklagernd = data().deepCopy(fields()[6].schema(), other.isBanklagernd);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.domiAddrId)) {
        this.domiAddrId = data().deepCopy(fields()[7].schema(), other.domiAddrId);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.mainAddrId)) {
        this.mainAddrId = data().deepCopy(fields()[8].schema(), other.mainAddrId);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.mainAddresse)) {
        this.mainAddresse = data().deepCopy(fields()[9].schema(), other.mainAddresse);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.isJoint)) {
        this.isJoint = data().deepCopy(fields()[10].schema(), other.isJoint);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.relationList)) {
        this.relationList = data().deepCopy(fields()[11].schema(), other.relationList);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.force)) {
        this.force = data().deepCopy(fields()[12].schema(), other.force);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.hash)) {
        this.hash = data().deepCopy(fields()[13].schema(), other.hash);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
    }

    /**
     * Creates a Builder by copying an existing JoinedBpAddrV2 instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.com.github.bohunn.JoinedBpAddrV2 other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.bpObjId)) {
        this.bpObjId = data().deepCopy(fields()[0].schema(), other.bpObjId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.bpName)) {
        this.bpName = data().deepCopy(fields()[1].schema(), other.bpName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bpNr)) {
        this.bpNr = data().deepCopy(fields()[2].schema(), other.bpNr);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.closeDate)) {
        this.closeDate = data().deepCopy(fields()[3].schema(), other.closeDate);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.isMa)) {
        this.isMa = data().deepCopy(fields()[4].schema(), other.isMa);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.isVip)) {
        this.isVip = data().deepCopy(fields()[5].schema(), other.isVip);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.isBanklagernd)) {
        this.isBanklagernd = data().deepCopy(fields()[6].schema(), other.isBanklagernd);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.domiAddrId)) {
        this.domiAddrId = data().deepCopy(fields()[7].schema(), other.domiAddrId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.mainAddrId)) {
        this.mainAddrId = data().deepCopy(fields()[8].schema(), other.mainAddrId);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.mainAddresse)) {
        this.mainAddresse = data().deepCopy(fields()[9].schema(), other.mainAddresse);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.isJoint)) {
        this.isJoint = data().deepCopy(fields()[10].schema(), other.isJoint);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.relationList)) {
        this.relationList = data().deepCopy(fields()[11].schema(), other.relationList);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.force)) {
        this.force = data().deepCopy(fields()[12].schema(), other.force);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.hash)) {
        this.hash = data().deepCopy(fields()[13].schema(), other.hash);
        fieldSetFlags()[13] = true;
      }
    }

    /**
      * Gets the value of the 'bpObjId' field.
      * obj_bp id
      * @return The value.
      */
    public long getBpObjId() {
      return bpObjId;
    }


    /**
      * Sets the value of the 'bpObjId' field.
      * obj_bp id
      * @param value The value of 'bpObjId'.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder setBpObjId(long value) {
      validate(fields()[0], value);
      this.bpObjId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bpObjId' field has been set.
      * obj_bp id
      * @return True if the 'bpObjId' field has been set, false otherwise.
      */
    public boolean hasBpObjId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bpObjId' field.
      * obj_bp id
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder clearBpObjId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'bpName' field.
      * @return The value.
      */
    public java.lang.String getBpName() {
      return bpName;
    }


    /**
      * Sets the value of the 'bpName' field.
      * @param value The value of 'bpName'.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder setBpName(java.lang.String value) {
      validate(fields()[1], value);
      this.bpName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'bpName' field has been set.
      * @return True if the 'bpName' field has been set, false otherwise.
      */
    public boolean hasBpName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'bpName' field.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder clearBpName() {
      bpName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'bpNr' field.
      * obj_bp key id 11
      * @return The value.
      */
    public java.lang.String getBpNr() {
      return bpNr;
    }


    /**
      * Sets the value of the 'bpNr' field.
      * obj_bp key id 11
      * @param value The value of 'bpNr'.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder setBpNr(java.lang.String value) {
      validate(fields()[2], value);
      this.bpNr = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'bpNr' field has been set.
      * obj_bp key id 11
      * @return True if the 'bpNr' field has been set, false otherwise.
      */
    public boolean hasBpNr() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'bpNr' field.
      * obj_bp key id 11
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder clearBpNr() {
      bpNr = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'closeDate' field.
      * @return The value.
      */
    public java.lang.String getCloseDate() {
      return closeDate;
    }


    /**
      * Sets the value of the 'closeDate' field.
      * @param value The value of 'closeDate'.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder setCloseDate(java.lang.String value) {
      validate(fields()[3], value);
      this.closeDate = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'closeDate' field has been set.
      * @return True if the 'closeDate' field has been set, false otherwise.
      */
    public boolean hasCloseDate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'closeDate' field.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder clearCloseDate() {
      closeDate = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'isMa' field.
      * @return The value.
      */
    public boolean getIsMa() {
      return isMa;
    }


    /**
      * Sets the value of the 'isMa' field.
      * @param value The value of 'isMa'.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder setIsMa(boolean value) {
      validate(fields()[4], value);
      this.isMa = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'isMa' field has been set.
      * @return True if the 'isMa' field has been set, false otherwise.
      */
    public boolean hasIsMa() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'isMa' field.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder clearIsMa() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'isVip' field.
      * @return The value.
      */
    public boolean getIsVip() {
      return isVip;
    }


    /**
      * Sets the value of the 'isVip' field.
      * @param value The value of 'isVip'.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder setIsVip(boolean value) {
      validate(fields()[5], value);
      this.isVip = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'isVip' field has been set.
      * @return True if the 'isVip' field has been set, false otherwise.
      */
    public boolean hasIsVip() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'isVip' field.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder clearIsVip() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'isBanklagernd' field.
      * @return The value.
      */
    public boolean getIsBanklagernd() {
      return isBanklagernd;
    }


    /**
      * Sets the value of the 'isBanklagernd' field.
      * @param value The value of 'isBanklagernd'.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder setIsBanklagernd(boolean value) {
      validate(fields()[6], value);
      this.isBanklagernd = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'isBanklagernd' field has been set.
      * @return True if the 'isBanklagernd' field has been set, false otherwise.
      */
    public boolean hasIsBanklagernd() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'isBanklagernd' field.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder clearIsBanklagernd() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'domiAddrId' field.
      * Domicil Address object id
      * @return The value.
      */
    public long getDomiAddrId() {
      return domiAddrId;
    }


    /**
      * Sets the value of the 'domiAddrId' field.
      * Domicil Address object id
      * @param value The value of 'domiAddrId'.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder setDomiAddrId(long value) {
      validate(fields()[7], value);
      this.domiAddrId = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'domiAddrId' field has been set.
      * Domicil Address object id
      * @return True if the 'domiAddrId' field has been set, false otherwise.
      */
    public boolean hasDomiAddrId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'domiAddrId' field.
      * Domicil Address object id
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder clearDomiAddrId() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'mainAddrId' field.
      * @return The value.
      */
    public long getMainAddrId() {
      return mainAddrId;
    }


    /**
      * Sets the value of the 'mainAddrId' field.
      * @param value The value of 'mainAddrId'.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder setMainAddrId(long value) {
      validate(fields()[8], value);
      this.mainAddrId = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'mainAddrId' field has been set.
      * @return True if the 'mainAddrId' field has been set, false otherwise.
      */
    public boolean hasMainAddrId() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'mainAddrId' field.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder clearMainAddrId() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'mainAddresse' field.
      * @return The value.
      */
    public java.lang.String getMainAddresse() {
      return mainAddresse;
    }


    /**
      * Sets the value of the 'mainAddresse' field.
      * @param value The value of 'mainAddresse'.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder setMainAddresse(java.lang.String value) {
      validate(fields()[9], value);
      this.mainAddresse = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'mainAddresse' field has been set.
      * @return True if the 'mainAddresse' field has been set, false otherwise.
      */
    public boolean hasMainAddresse() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'mainAddresse' field.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder clearMainAddresse() {
      mainAddresse = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'isJoint' field.
      * @return The value.
      */
    public boolean getIsJoint() {
      return isJoint;
    }


    /**
      * Sets the value of the 'isJoint' field.
      * @param value The value of 'isJoint'.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder setIsJoint(boolean value) {
      validate(fields()[10], value);
      this.isJoint = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'isJoint' field has been set.
      * @return True if the 'isJoint' field has been set, false otherwise.
      */
    public boolean hasIsJoint() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'isJoint' field.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder clearIsJoint() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'relationList' field.
      * Bp-Person relation list
      * @return The value.
      */
    public java.util.List<avro.com.github.bohunn.RelationItem> getRelationList() {
      return relationList;
    }


    /**
      * Sets the value of the 'relationList' field.
      * Bp-Person relation list
      * @param value The value of 'relationList'.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder setRelationList(java.util.List<avro.com.github.bohunn.RelationItem> value) {
      validate(fields()[11], value);
      this.relationList = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'relationList' field has been set.
      * Bp-Person relation list
      * @return True if the 'relationList' field has been set, false otherwise.
      */
    public boolean hasRelationList() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'relationList' field.
      * Bp-Person relation list
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder clearRelationList() {
      relationList = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'force' field.
      * technical field to force onbase synchronization
      * @return The value.
      */
    public int getForce() {
      return force;
    }


    /**
      * Sets the value of the 'force' field.
      * technical field to force onbase synchronization
      * @param value The value of 'force'.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder setForce(int value) {
      validate(fields()[12], value);
      this.force = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'force' field has been set.
      * technical field to force onbase synchronization
      * @return True if the 'force' field has been set, false otherwise.
      */
    public boolean hasForce() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'force' field.
      * technical field to force onbase synchronization
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder clearForce() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'hash' field.
      * @return The value.
      */
    public java.lang.String getHash() {
      return hash;
    }


    /**
      * Sets the value of the 'hash' field.
      * @param value The value of 'hash'.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder setHash(java.lang.String value) {
      validate(fields()[13], value);
      this.hash = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'hash' field has been set.
      * @return True if the 'hash' field has been set, false otherwise.
      */
    public boolean hasHash() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'hash' field.
      * @return This builder.
      */
    public avro.com.github.bohunn.JoinedBpAddrV2.Builder clearHash() {
      hash = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public JoinedBpAddrV2 build() {
      try {
        JoinedBpAddrV2 record = new JoinedBpAddrV2();
        record.bpObjId = fieldSetFlags()[0] ? this.bpObjId : (java.lang.Long) defaultValue(fields()[0]);
        record.bpName = fieldSetFlags()[1] ? this.bpName : (java.lang.String) defaultValue(fields()[1]);
        record.bpNr = fieldSetFlags()[2] ? this.bpNr : (java.lang.String) defaultValue(fields()[2]);
        record.closeDate = fieldSetFlags()[3] ? this.closeDate : (java.lang.String) defaultValue(fields()[3]);
        record.isMa = fieldSetFlags()[4] ? this.isMa : (java.lang.Boolean) defaultValue(fields()[4]);
        record.isVip = fieldSetFlags()[5] ? this.isVip : (java.lang.Boolean) defaultValue(fields()[5]);
        record.isBanklagernd = fieldSetFlags()[6] ? this.isBanklagernd : (java.lang.Boolean) defaultValue(fields()[6]);
        record.domiAddrId = fieldSetFlags()[7] ? this.domiAddrId : (java.lang.Long) defaultValue(fields()[7]);
        record.mainAddrId = fieldSetFlags()[8] ? this.mainAddrId : (java.lang.Long) defaultValue(fields()[8]);
        record.mainAddresse = fieldSetFlags()[9] ? this.mainAddresse : (java.lang.String) defaultValue(fields()[9]);
        record.isJoint = fieldSetFlags()[10] ? this.isJoint : (java.lang.Boolean) defaultValue(fields()[10]);
        record.relationList = fieldSetFlags()[11] ? this.relationList : (java.util.List<avro.com.github.bohunn.RelationItem>) defaultValue(fields()[11]);
        record.force = fieldSetFlags()[12] ? this.force : (java.lang.Integer) defaultValue(fields()[12]);
        record.hash = fieldSetFlags()[13] ? this.hash : (java.lang.String) defaultValue(fields()[13]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<JoinedBpAddrV2>
    WRITER$ = (org.apache.avro.io.DatumWriter<JoinedBpAddrV2>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<JoinedBpAddrV2>
    READER$ = (org.apache.avro.io.DatumReader<JoinedBpAddrV2>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.bpObjId);

    out.writeString(this.bpName);

    out.writeString(this.bpNr);

    if (this.closeDate == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.closeDate);
    }

    out.writeBoolean(this.isMa);

    out.writeBoolean(this.isVip);

    out.writeBoolean(this.isBanklagernd);

    out.writeLong(this.domiAddrId);

    out.writeLong(this.mainAddrId);

    if (this.mainAddresse == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.mainAddresse);
    }

    out.writeBoolean(this.isJoint);

    if (this.relationList == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.relationList.size();
      out.writeArrayStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (avro.com.github.bohunn.RelationItem e0: this.relationList) {
        actualSize0++;
        out.startItem();
        if (e0 == null) {
          out.writeIndex(0);
          out.writeNull();
        } else {
          out.writeIndex(1);
          e0.customEncode(out);
        }
      }
      out.writeArrayEnd();
      if (actualSize0 != size0)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

    out.writeInt(this.force);

    out.writeString(this.hash);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.bpObjId = in.readLong();

      this.bpName = in.readString();

      this.bpNr = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.closeDate = null;
      } else {
        this.closeDate = in.readString();
      }

      this.isMa = in.readBoolean();

      this.isVip = in.readBoolean();

      this.isBanklagernd = in.readBoolean();

      this.domiAddrId = in.readLong();

      this.mainAddrId = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.mainAddresse = null;
      } else {
        this.mainAddresse = in.readString();
      }

      this.isJoint = in.readBoolean();

      if (in.readIndex() != 1) {
        in.readNull();
        this.relationList = null;
      } else {
        long size0 = in.readArrayStart();
        java.util.List<avro.com.github.bohunn.RelationItem> a0 = this.relationList;
        if (a0 == null) {
          a0 = new SpecificData.Array<avro.com.github.bohunn.RelationItem>((int)size0, SCHEMA$.getField("relationList").schema().getTypes().get(1));
          this.relationList = a0;
        } else a0.clear();
        SpecificData.Array<avro.com.github.bohunn.RelationItem> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<avro.com.github.bohunn.RelationItem>)a0 : null);
        for ( ; 0 < size0; size0 = in.arrayNext()) {
          for ( ; size0 != 0; size0--) {
            avro.com.github.bohunn.RelationItem e0 = (ga0 != null ? ga0.peek() : null);
            if (in.readIndex() != 1) {
              in.readNull();
              e0 = null;
            } else {
              if (e0 == null) {
                e0 = new avro.com.github.bohunn.RelationItem();
              }
              e0.customDecode(in);
            }
            a0.add(e0);
          }
        }
      }

      this.force = in.readInt();

      this.hash = in.readString();

    } else {
      for (int i = 0; i < 14; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.bpObjId = in.readLong();
          break;

        case 1:
          this.bpName = in.readString();
          break;

        case 2:
          this.bpNr = in.readString();
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.closeDate = null;
          } else {
            this.closeDate = in.readString();
          }
          break;

        case 4:
          this.isMa = in.readBoolean();
          break;

        case 5:
          this.isVip = in.readBoolean();
          break;

        case 6:
          this.isBanklagernd = in.readBoolean();
          break;

        case 7:
          this.domiAddrId = in.readLong();
          break;

        case 8:
          this.mainAddrId = in.readLong();
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.mainAddresse = null;
          } else {
            this.mainAddresse = in.readString();
          }
          break;

        case 10:
          this.isJoint = in.readBoolean();
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.relationList = null;
          } else {
            long size0 = in.readArrayStart();
            java.util.List<avro.com.github.bohunn.RelationItem> a0 = this.relationList;
            if (a0 == null) {
              a0 = new SpecificData.Array<avro.com.github.bohunn.RelationItem>((int)size0, SCHEMA$.getField("relationList").schema().getTypes().get(1));
              this.relationList = a0;
            } else a0.clear();
            SpecificData.Array<avro.com.github.bohunn.RelationItem> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<avro.com.github.bohunn.RelationItem>)a0 : null);
            for ( ; 0 < size0; size0 = in.arrayNext()) {
              for ( ; size0 != 0; size0--) {
                avro.com.github.bohunn.RelationItem e0 = (ga0 != null ? ga0.peek() : null);
                if (in.readIndex() != 1) {
                  in.readNull();
                  e0 = null;
                } else {
                  if (e0 == null) {
                    e0 = new avro.com.github.bohunn.RelationItem();
                  }
                  e0.customDecode(in);
                }
                a0.add(e0);
              }
            }
          }
          break;

        case 12:
          this.force = in.readInt();
          break;

        case 13:
          this.hash = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










