akhq:
  metrics:
    enabled: false
  connections:
    kafka-cluster:
      properties:
        bootstrap.servers: kafka:29092
      schema-registry:
        url: http://schema-registry:8081
        type: "confluent"